service: tipo-nivel-service

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'local'}
  region: us-east-1

  # Configuración de CORS global para toda la API de este servicio
  http:
    cors:
      origin: 'http://localhost:3000'
      headers:
        - Content-Type
        - Authorization
      allowCredentials: true

  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}"

plugins:
  - serverless-python-requirements
  - serverless-localstack
  - serverless-offline  # <-- Plugin añadido

custom:
  tableName: sgeac-tipos-nivel-table-${self:provider.stage}
  pythonRequirements:
    dockerizePip: true
  localstack:
    stages:
      - local
  serverless-offline:
    httpPort: 3008 # Puerto para el servicio de asistencia
    host: '0.0.0.0'
    lambdaPort: 4008 # Puerto para las funciones Lambda
    noPrependStageInUrl: true

functions:
  createTipoNivel:
    handler: create_t_nivel.handler
    description: "Crea un nuevo tipo de nivel."
    events:
      - http:
          path: /tipos-nivel
          method: post
          

  listTiposNivel:
    handler: list_t_nivel.handler
    description: "Lista todos los tipos de nivel."
    events:
      - http:
          path: /tipos-nivel
          method: get
          

  getTipoNivelById:
    handler: get_t_nivel.handler
    description: "Obtiene un tipo de nivel por su ID."
    events:
      - http:
          path: /tipos-nivel/{id}
          method: get
          

  updateTipoNivel:
    handler: up_t_nivel.handler
    description: "Actualiza los datos de un tipo de nivel."
    events:
      - http:
          path: /tipos-nivel/{id}
          method: put
          

  deleteTipoNivel:
    handler: delete_t_nivel.handler
    description: "Elimina un tipo de nivel."
    events:
      - http:
          path: /tipos-nivel/{id}
          method: delete
          

resources:
  Resources:
    TiposNivelTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1