service: calificaciones-service

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'local'}
  region: us-east-1

  # Configuración de CORS global para toda la API de este servicio
  http:
    cors:
      origin: 'http://localhost:3000'
      headers:
        - Content-Type
        - Authorization
      allowCredentials: true


  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
    ALUMNO_INDEX: ${self:custom.alumnoIndexName}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Query"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}/index/*"

plugins:
  - serverless-python-requirements
  - serverless-localstack
  - serverless-offline  # <-- Plugin añadido

custom:
  tableName: sgeac-calificaciones-table-${self:provider.stage}
  alumnoIndexName: alumno-id-index
  pythonRequirements:
    dockerizePip: true
  localstack:
    stages:
      - local
  serverless-offline:
    httpPort: 3005 # Puerto para el servicio de asistencia
    host: '0.0.0.0'
    lambdaPort: 4005 # Puerto para las funciones Lambda
    noPrependStageInUrl: true

functions:
  registrarCalificacion:
    handler: registro_calif.handler
    description: "Registra una nueva calificación para un alumno."
    events:
      - http:
          path: /calificaciones
          method: post
          

  listarCalificacionesPorAlumno:
    handler: list_x_alumno.handler
    description: "Lista todas las calificaciones de un alumno específico."
    events:
      - http:
          path: /calificaciones/alumno/{alumno_id}
          method: get
          
  
  updateCalificacion:
    handler: up_calif.handler
    description: "Actualiza una calificación existente."
    events:
      - http:
          path: /calificaciones/{id} # Usamos el ID de la calificación
          method: put
          

  
  deleteCalificacion:
    handler: delete_calif.handler
    description: "Elimina una calificación por su ID."
    events:
      - http:
          path: /calificaciones/{id}
          method: delete
          
resources:
  Resources:
    CalificacionesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: alumno_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.alumnoIndexName}
            KeySchema:
              - AttributeName: alumno_id
                KeyType: HASH
            Projection: { ProjectionType: ALL }
            ProvisionedThroughput: { ReadCapacityUnits: 1, WriteCapacityUnits: 1 }
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1