service: sucursal-service

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'local'}
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}"

plugins:
  - serverless-python-requirements
  - serverless-localstack

custom:
  tableName: sgeac-sucursales-table-${self:provider.stage}
  pythonRequirements:
    dockerizePip: true
  localstack:
    stages:
      - local
    host: http://localhost
    autostart: false

functions:
  createSucursal:
    handler: create_sucursal.handler
    description: "Crea una nueva sucursal."
    events:
      - http:
          path: /sucursales
          method: post
          cors: true

  listSucursales:
    handler: list_sucursal.handler
    description: "Lista todas las sucursales."
    events:
      - http:
          path: /sucursales
          method: get
          cors: true

  getSucursalById:
    handler: get_sucursal.handler
    description: "Obtiene una sucursal por su ID."
    events:
      - http:
          path: /sucursales/{id}
          method: get
          cors: true

  updateSucursal:
    handler: update_sucursal.handler
    description: "Actualiza los datos de una sucursal."
    events:
      - http:
          path: /sucursales/{id}
          method: put
          cors: true

  deleteSucursal:
    handler: delete_sucursal.handler
    description: "Elimina una sucursal."
    events:
      - http:
          path: /sucursales/{id}
          method: delete
          cors: true

resources:
  Resources:
    SucursalesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1